### ISSUE TITLE
Please update for LidarLiteV4

### ISSUE THREAD

**Issue by philletourneau** [adafruit/Adafruit_CircuitPython_LIDARLite#19] opened 2022-05-14 18:24 UTC
Can you please update this library to support the new LidarLiteV4?

I spent over an hour trying to set it up with this library, as the library does not specifically specify that it doesn't work with this model, and it is a module that is sold on the Adafruit store.

Thanks!

**Comment by ladyada** [comment] 2022-05-15 14:12
thanks! closing as duplicate of
https://github.com/adafruit/Adafruit_CircuitPython_LIDARLite/issues/14

**Closed as completed by ladyada** 2022-05-15 14:12 UTC
